version: "3"
services:
  api:
    build: ./api
    ports: 
      - 8000:8000
  ui:
    build: ./ui
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - api
    environment:
      MONGODB_URI: 
    
