apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    name: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api-image
          image: meeckey/sample-app-api
          env:
            - name: MONGODB_URI
              value: mongodb+srv://kube-post:pW46yOXdYRSU0RVd@cluster0.6lrvr.mongodb.net/?retryWrites=true&w=majority